apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nkendyal9-poi-map-app-dev
  annotations:
    argocd/app-name: nkendyal9-poi-map-app-dev
    backstage.io/kubernetes-id: nkendyal9-poi-map-app
    backstage.io/kubernetes-namespace: nkendyal9
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-atl/nkendyal9-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/dev-pipelines/ns/nkendyal9/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/k8s/ns/nkendyal9/deployments/nkendyal9-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.j0i9yf30.eastus2.aroapp.io/#https://github.com/rhdh-atl/nkendyal9-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://nkendyal9-poi-map-app-nkendyal9.apps.j0i9yf30.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/nkendyal9"
  system: workshop-system-nkendyal9
  consumesApis:
    - gateway-api-nkendyal9
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-nkendyal9
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/nkendyal9"
